version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: petrevichev/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: petrevichev/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
    restart: unless-stopped
  
  gateway:
    image: petrevichev/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
    restart: unless-stopped