version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: petrevichev/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./data:/app/data
    depends_on:
      - db
  frontend:
    image: petrevichev/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
  
  gateway:
    image: petrevichev/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - ./docs:/usr/share/nginx/html/api/docs/
