version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: petrevichev/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: petrevichev/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend
  
  gateway:
    image: petrevichev/foodgram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/app/media