# Generated by Django 3.2.16 on 2025-02-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0003_auto_20250220_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'verbose_name': 'Короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='food_recipes.recipe'),
        ),
    ]
