# Generated by Django 3.2.16 on 2024-12-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0003_auto_20241224_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientforrecipe',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
