# Generated by Django 3.2.16 on 2024-12-24 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0005_auto_20241224_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientforrecipe',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredientforrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_for_recipe', to='food_recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientforrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_for_recipe', to='food_recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='food_recipes.IngredientForRecipe', to='food_recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
