# Generated by Django 3.2.16 on 2025-02-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0005_auto_20250224_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientforrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_for', to='food_recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
