# Generated by Django 3.2.16 on 2025-02-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0007_auto_20250224_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientforrecipe',
            options={'verbose_name': 'Ингредиенты рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
    ]
