# Generated by Django 3.2.16 on 2024-12-26 12:28

from django.db import migrations, models
import food_recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0007_auto_20241224_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=64, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, validators=[food_recipes.validators.validate_slug], verbose_name='Слаг'),
        ),
    ]
