# Generated by Django 3.2.16 on 2025-02-27 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0008_alter_ingredientforrecipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'ordering': ('user',), 'verbose_name': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientforrecipe',
            options={'ordering': ('ingredient',), 'verbose_name': 'Ингредиенты рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ('user',), 'verbose_name': 'Список покупок'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='food_recipes.IngredientForRecipe', to='food_recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='food_recipes.Tag', verbose_name='Теги'),
        ),
    ]
