# Generated by Django 3.2.16 on 2025-01-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0008_auto_20241226_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
