# Generated by Django 3.2.16 on 2025-02-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0012_auto_20250227_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_id',
        ),
    ]
