# Generated by Django 3.2.16 on 2025-02-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0013_remove_recipe_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
