# Generated by Django 3.2.16 on 2025-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes', '0014_recipe_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
