# Generated by Django 3.2.16 on 2025-02-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username', 'date_joined'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
